In [1]:
import numpy as np
import pandas as pd


In [3]:
df=pd.read_csv("Position_Salaries.csv")
df.head()

Position  Level  Salary
0             Associate      1   45000
1  Jr Software Engineer      2   50000
2  Sr Software Engineer      3   60000
3           Team leader      4   80000
4               Manager      5  110000

In [17]:
x=df.iloc[:,1:2].values
x

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [5]:
y=df.iloc[:,-1].values
y

array([  45000,   50000,   60000,   80000,  110000,  150000,  200000,
        300000,  500000, 1000000])

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y)

In [18]:
from sklearn.neighbours import KNeighborsRegressor
knn=KNeighboursRegressor()
knn.fit(x_train,y_train)
y_pred=knn.predict(x_test)
y_pred

ModuleNotFoundError: No module named 'sklearn.neighbours'

In [6]:
import pandas as pd
import numpy as np


In [7]:
df=pd.read_csv("Position_Salaries.csv")

In [8]:
df

Position  Level   Salary
0             Associate      1    45000
1  Jr Software Engineer      2    50000
2  Sr Software Engineer      3    60000
3           Team leader      4    80000
4               Manager      5   110000
5                    VP      6   150000
6                   AVP      7   200000
7                  CTO       8   300000
8                   CEO      9   500000
9               Founder     10  1000000

In [11]:
x=df.iloc[:,1:2].values
x

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [12]:
y=df.iloc[:,-1].values
y

array([  45000,   50000,   60000,   80000,  110000,  150000,  200000,
        300000,  500000, 1000000])

In [14]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [16]:
from sklearn.tree import DecisionTreeRegressor
dtree=DecisionTreeRegressor()
dtree.fit(x_train,y_train)
dtree

DecisionTreeRegressor()